add support for packages of type roundcube-skin, fix sql execution an…
roundcube/plugin-installer pull request #26
Opened 2020-11-08 12:01 UTC by johndoh

…d other improvements

update of #24 for Composer V2.

I thought it might be handy to extend the plugin-installer to support packages of type roundcube-skin and not just roundcube-plugin that way third party skins can be distributed in the same way as plugins through composer.

Add some bug fixes:

    #15 check for a config file on .inc.php in the roundcube config dir before creating confic.inc.php in the plugin dir
    #23 small fix to avoid null reference error
    #19, #21 replace use of rcubeinitdb.sh and updatedb.sh with rcmail_utils::db_init() and rcmail_utils::db_update()
    if the config var was not already in config.inc.php then it was added with a extra semi colon at the end eg $config['plugins'] = array('plugin_name');; this has been fixed.

2021-05-23 09:09 UTC, alecpl requested changes

2021-05-23 09:09 UTC, alecpl commented on README.md
> +## Roundcube specifc composer.json params
a typo in "specifc".

2021-05-23 09:09 UTC, alecpl commented on src/Roundcube/Composer/PluginInstaller.php
> +        return $package_dir;
This method could be a one-liner.

2021-05-24 05:53 UTC, alecpl approved these changes
Approved, but @thomascube should also review this.

2021-05-26 19:14 UTC, thomascube commented
@johndoh Do you have an example skin that can be installed with this installer? I just like to see it work :-)

2021-05-26 21:10 UTC, johndoh commented
sure. if you add this to your `composer.json`:
```
    "repositories": [
        ...
        {
            "type": "vcs",
            "url": "https://github.com/johndoh/plugin-installer"
        },
        {
            "type": "vcs",
            "url": "https://github.com/johndoh/roundcube-sample-skin"
        }
    ],
    ...
    "require": {
        ...
        "roundcube/plugin-installer": "dev-roundcube-skin",
        "johndoh/sample-skin": "dev-master"
    }
```
it will install a very simple skin which extends Elastic. It changes the background colour of the watermark template (to blue) and changes the icons for the markasjunk plugin toolbar items (to thumbs up/down)

2021-06-19 19:49 UTC, merged